import streamlit as st

#MATERI RUANG GURU
#Header Pertama
st.header('Konsep Fluida Statis')
#Subheader 1
st.subheader('1. Fluida')
st.write('Zat yang menalami perubahan struktur atau deformasi kontinu saat diberikan tegangan geser, secara sederhana fluida adalah zat yang dapat mengalir.')

#Subheader 2        
st.subheader('2. Massa Jenis atau Densitas')
st.write('Perbandingan atau rasio antara massa zat dengan volume zat tersebut.')
col1, col2, col1 = st.columns(3)
with col2:
    st.latex(r'\rho=\frac{m}{V}')
st.write('Keterangan:')
st.write(r'$$\rho = \text{Massa Jenis atau Densitas} \,(kg/m^3)$$')
st.write(r'$$m = \text{Massa Benda} \,(kg)$$')
st.write(r'$$V = \text{Volume benda} \,(cm^3)$$')
st.markdown('###')

#Subheader 3
st.subheader('3. Viskositas')
st.write('Ukuran ketahanan fluida terhadap deformasi atau perubahan struktur, secara sederhana adalah tingkat kekentalan fluida.')
st.write('Semakin tinggi nilai viskositas maka fluida akan semakin kental, semakin rendah nilai viskositas maka fluida akan semakin encer.')
st.markdown('###')
st.write('---')


st.header('A. Tekanan')
st.write('Didalam subbab tekanan terdapat beberapa pembahasan yaitu, tekanan pada zat padat, tekanan hidrostatis, tekanan atmosfer, tekanan gauge, dan tekanan absolut. Berikut pembahasan secara singkatnya:')
#Subheader 1
st.subheader('1. Tekanan Pada Zat Padat')
st.write('Tekanan pada zat padat merupakan gaya yang bekerja pada luas bidang tekan. Dengan gambar dan rumus sebagai berikut:')
left_co, cent_co,last_co = st.columns(3)
with cent_co:
    st.image('https://unjac-my.sharepoint.com/personal/shelvyokvia_1302620035_mhs_unj_ac_id/Documents/120/Website%20Chatbot/image/Picture1.png?Web=1')
col3,col4 = st.columns(2, gap='medium')
with col3:
    st.latex(r'P = \frac{F}{A}')
with col4:
    st.latex(r'P = Tekanan (Pascal atau N/m^2)')
    st.latex(r'F = Gaya (N)')
    st.latex(r'A = Luas Permukaan (m^2)')
st.markdown('###')

#Subheader 2
st.subheader('2. Tekanan Hidrostatis')
st. write('Tekanan hidrostatis merupakan tekanan yang diberikan fluida statis (diam) dalam kedalaman tertentu. Tekanan fluida akibat beratnya sendiri. Tekanan hisrostatis berbanding lurus dengan kedalaman. Semakin dalam posisi di dalam fluida, tekanan hidrostatis yang dialami semakin besar karena berat fluida di atas posisi tersebut semakin besar. Berikut ilustrasi beserta gambarnya:')
left_co, cent_co,last_co = st.columns(3)
with cent_co:
    st.image('https://unjac-my.sharepoint.com/personal/shelvyokvia_1302620035_mhs_unj_ac_id/Documents/120/Website%20Chatbot/image/Picture2.png?Web=1')
col5,col6 = st.columns(2, gap='small')
with col5:
    st.latex(r'P_h = \rho{g}{h}')
with col6:
    st. write('Keterangan:')
    st.latex(r'P_h = Tekanan Hidrostatis (Pascal atau N/m^2)')
    st.latex(r'\rho = Massa Jenis fluida (kg/m^3)')
    st.latex(r'g = Percepatan gravitasi (m/s^2)')
    st.latex(r'h = Kedalaman (m)')
st.markdown('###')

#Subheader 3
st.subheader('3. Tekanan Atmosfer')
st.write('Tekanan atmosfer merupakan tekanan rata-rata udara dalam keadaan normal di atas permukaan air laut. Dimana nilai tekanan atmosfer sebagai berikut')
left_co, cent_co,last_co = st.columns(3)
with cent_co:
    st.latex(r'P_0 = 101325 P_a')
    st.latex(r'P_0 = 1,01*10^5 P_a = 1 atm')
st.markdown('###')

#Subheader 4
st.subheader('4. Tekanan Absolut')
st.write('Tekanan absolut disebut juga tekanan mutlak atau total sebuah titik ukur fluida. Tekanan sebenarnya yang dirasakan di dalam suatu fluida. Dengan rumus sebagai berikut:')
left_co, cent_co,last_co = st.columns(3)
with cent_co:
    st.latex(r'P_a={\rho}{g}{h} + P_0')
st.write('Keterangan:')
st.write(r'$$P_a = \text{Tekanan Absolut} \,({Pascal} \text{ atau } \,{N/m^2})$$')
st.write(r'$$P_0 = \text{Tekanan Atmosfer} \,({Pascal} \text{ atau } \,{N/m^2})$$')
st.write(r'$$\rho = \text{Massa Jenis fluida} \,(kg/m^3)$$')
st.write(r'$$g = \text{Percepatan gravitasi} \,(m/s^2)$$')
st.write(r'$$h = \text{Kedalaman} \,(m)$$')
st.markdown('###')

#Subheader 5
st.subheader('5. Tekanan Gauge')
st.write('Tekanan gauge merupakan selisih antara tekanan total (absolut) suatu titik ukur fluida dengan tekanan atmosfer. Tekanan pada alat pengukur tekanan fluida sudah dikalibrasi sehingga tekanan atmosfer tidak terbaca, yang terbaca pada alat pengukur hanya tekanan hidrostatisnya. Tekanan hidrostatis yang terbaca ini disebut sebagai tekanan gauge. Berikut ilustrasi dan persamaannya:')
left_co,last_co = st.columns(2)
with last_co:
    st.write('')
    st.image('image/Picture3.png',caption='Gambar 3. Alat Pengukur Tekanan Fluida', width=100)
    st.write('')     
with left_co:
    st.latex(r'P_{abs} = P_{gauge} + P_0')
    st.write('Keterangan:')
    st.write(r'$$P_{abs} = \text{Tekanan Absolut} \,(Pascal)$$')
    st.write(r'$$P_{gauge} = \text{Tekanan gauge} \,(Pascal)$$')
    st.write(r'$$P_0 = \text{Hidrosfer} \,(Pascal)$$')
    st.markdown('###')
    st.write('---')

#Header Kedua
st.header('B. Hukum Hidrostatis')
st.write('Didalam subbab hukum pokok hidrostatis terdapat 2 topik pembahasan, yaitu mengenai hukum pokok hidrostatis dan pipa U. Pada subbab hukum pokok hidrostatis membahas tentang pengertian hukum pokok hidrostatis, barometer, dan manometer. Berikut penjelasan materi secara singkat:')

#Subheader 1
st.subheader('1. Hukum Pokok Hidrostatis')
st.write('Hukum pokok hidrostatis disini membahas 3 topik, yaitu hukum pokok, barometer, dan manometer. Berikut penjelasan lebih lanjut:')
st.write('Dalam bejana berhubungan tiap titik fluida dengan kedudukan yang sama terhadap acuan akan mempunyai nilai tekanan absolut (mutlak) yang sama. Perhatikan gambar di bawah ini, tekanan di keempat titik ini akan sama, karena keempat kolom masih terhubung.')
left_co, cent_co,last_co = st.columns(3)
with cent_co:
    st.image('image/Picture4.png', caption='Tekanan Bidang Datar')
st.write('Jika fluida saat digabungkan dalam 1 wadah dan tidak tercampur, maka fluida dengan massa jenis terbesar akan berada pada lapisan paling bawah, dan massa jenis terkecil pada lapisan paling atas.')
left_co, cent_co,last_co = st.columns(3)
with cent_co:
    st.image('https://unjac-my.sharepoint.com/personal/shelvyokvia_1302620035_mhs_unj_ac_id/Documents/120/Website%20Chatbot/image/Picture5.png?Web=1')
st.write('Jika fluida seperti gambar diatas, maka massa jenisnya dapat terlihat seperti berikut:')
st.latex(r'\rho_A<\rho_B<\rho_C')
st.markdown('###')

##Barometer
st.markdown('- Barometer')
st.write('Barometer merupakan alat yang digunakan untuk mengukur tekanan udara pada atmosfer. (1 atm ditunjukkan oleh kenaikan raksa dalam tabung hampa setinggi 760 mm).')
left_co, cent_co,last_co = st.columns(3)
with cent_co:
    st.image('image/Picture6.png', caption='Gambar 6. Barometer')
st.markdown('###')

##Manometer
st.markdown('- Manometer')
st.write('Manometer adalah alat yang digunakan untuk mengukur tekanan fluida dalam suatu bejana dengan menggunakan ketinggian kolom fluida. Beberapa jenis manometer yaitu manometer logam, manometer digital, dan manometer zat cair (klasik). Fluida yang biasa digunakan adalah raksa.')
left_co, cent_co,last_co = st.columns(3)
with cent_co:
    st.image('image/Picture7.png', caption='Gambar 7. Manometer Terbuka')
    st.latex(r'P_{gas} = \rho{g}(h_B) + P_{atm}')
    st.image('image/Picture8.png', caption='Gambar 8. Manometer Tertutup')
    st.latex(r'P_{gas} = \rho{g}(h_B) + P_{atm}')        
st.write('Keterangan:')
st.write('$P gas$ = Tekanan gas yang terukur (Pa)')
st.write('$P atm$ = Tekanan atmosfer (Pa)')
st.write('$P_u$ = Tekanan gas di ujung kolom manometer tertutup (Pa)')
st.write('$ \rho $ = Densitas atau massa jenis fluida $(kg/m^3)$')
st.write('Percepatan gravitasi $(m/s^2 )$')
st.write('h=Kedalaman (m)')
st.markdown('###')

#Subheader 2
st.subheader('2. Pipa U')
st.write('Pipa U merupakan alat eksperimen pipa/tabung dari bahan transparan untuk mengukur nilai densitas suatu fluida (cairan) dengan perbandingan ketinggian fluida dalam pipa terhadap acuan. Kedua kolom pipa U dapat berisi 2 jenis fluida, yang berbeda, namun tekanan absolut di titik A dan B akan selalu sama karena kedua titik ini sebidang. Berikut persamaan beserta gambarnya:')
left_co, cent_co, last_co = st.columns(3)
with left_co:
    st.image('image/Picture9.png', caption='Gambar 9. Pipa U Berisi 2 Jenis Fluida')
st.write()    
with cent_co:
    st.image('image/Picture10.png', caption='Gambar 10. Pipa U Berisi 3 Jenis Fluida')
with last_co:
    st.image('image/Picture11.png', caption='Gambar 11. Pipa U Berisi 3 Jenis Fluida (2)')
st.write('Persamaan untuk Pipa U Berisis 2 Jenis Fluida, sebagai berikut:')    
st.latex(r'{\rho_a}*{g}*{h_a} = {\rho_b}*{g}*{h_b}')
st.latex(r'\frac{\rho_a}{\rho_b} = \frac{h_a}{h_b}')
st.write('Persamaan untuk Pipa U Berisis 3 Jenis Fluida (1), sebagai berikut:')
st.latex(r'{\rho_a}*{g}*{h_a} + {\rho_c}*{g}*{h_c} = {\rho_b}*{g}*{h_b}')
st.write('Persamaan untuk Pipa U Berisis 3 Jenis Fluida (2), sebagai berikut:')
st.latex(r'{\rho_a}*{g}*{h_a} + {\rho_b}*{g}*{h_b} = {\rho_c}*{g}*{h_c}')
st.write('Keterangan:')
st.write(r'$$\rho = \text{Densitas atau massa jenis} \, (kg/m^3)$$')
st.write('$g$ = Percepatan gravitasi $m/s^2$')
st.write('$h$ = Tinggi kolom fluida dalam tabung terhadap acuan $(m)$')
st.markdown('###')
st.write('---')

#Header Ketiga
st.header('C. Hukum Pascal')
st.write('Dalam subbab hukum pascal, terdapat beberapa materi yang dipelajari di dalamnya, yaitu bunyi hukum pascal, persamaan hukum pascal, dan sistem hidrolik.')
st.subheader('1. Bunyi Hukum Pascal')
st.write('Menurut ilmuan perancis, yaitu Blaise Pascal (1623-1662) bunyi hukum Pascal yaitu “Jika dalam sebuah sistem fluida tertutup diberikan tekanan, tekanan tersebut akan disalurkan ke segala arah dengan besar yang sama”.')
st.markdown('###')
st.subheader('2. Persamaan Hukum Pascal')
st.write('Berdasarkan bunyi hukum pascal yang menyebutkan jika tekanan yang diberikan pada suatu fluida dalam ruang tertutup diteruskan sama besar ke semua arah, maka persamaan hukum pascal adalah sebagai berikut:')
left_co, cent_co,last_co = st.columns(3)
with cent_co:
    st.image('image/Picture12.png', caption='Gambar 12. Ilustrasi Persamaan hukum Pascal')
    st.latex(r'P_1 = P_2')
    st.latex(r'\frac{F_1}{A_1} = \frac{F_2}{A_2}')
    st.latex(r'\frac{F_1}{F_2} = \frac{A_1}{A_2}')
    st.latex(r'\frac{F_1}{F_2} = (\frac{r_1}{r_2})^2')
    st.latex(r'\frac{F_1}{F_2} = (\frac{d_1}{d_2})^2')
st.write('Keterangan:')
st.write(r'$$P = \text{Tekanan} \, (N/m^2 \text{atau} \, Pa)$$')
st.write(r'$$F = \text{gaya} \,(N)$$')
st.write(r'$$A = \text{Luas Penampang Piston} \,(m^2)$$')
st.write(r'$$r = \text{Jari-jari piston} \,(m)$$')
st.write(r'$$d = \text{Diameter piston} \,(m)$$')
st.markdown('###')
st.subheader('3. Sistem Hidrolik')
st.write('Sistem hidrolik berasal dari Bahasa Yunani kuno hidro (air) dan ulos (pipa). Sistem hidrolik ini memanfaatkan prinsip hukum pokok hidrostatis dan hukum Pascal. Contoh pemanfaatan hidrolik yaitu dongkrak hidrolik, rem hidrolik, dan pompa hidrolik.')
st.markdown("<img src='https://unjac-my.sharepoint.com/personal/shelvyokvia_1302620035_mhs_unj_ac_id/Documents/120/Website%20Chatbot/image/Picture13.png?Web=1' width='400' style='display: block; margin: 0 auto;'>", unsafe_allow_html=True)
st.write('')
st.write('Kelebihan sistem hidrolik, yaitu memiliki daya tahan terhadap keausan, mudah pengaturan gaya yang dibutuhkan dan digunakan, penyaluran daya yang besar, getaran yang timbul relative kecil, dan energi terbuang dari sistem lebih kecil.')
st.write('Kekurangan sistem hidrolik, yaitu perawatan terhadap fluida harus berkala, pemilihan fluida harus tepat tidak boleh sembarangan, bahaya tekanan tinggi fluida dalam sistem, dan sistem harus tertutup rapat (tanpa kebocoran).')
st.markdown('###')
st.write('---')

#Header Keempat
st.header('D. Hukum Archimedes')
st.write('Di dalam subbab hukum Archimedes ini akan membahas mengenai pengertian hukum Archimedes, keadaan benda di fluida, dan penerapan hukum Archimedes. Untuk penjelasan singkatnya sebagai berikut:')
st.subheader('1. Bunyi Hukum Archimedes')
st.write('Bunyi Hukum Archimedes, yaitu “Jika sebuah benda dimasukkan ke dalam fluida, maka benda itu akan mendapatkan gaya apung sebesar berat fluida yang dipindahkan” – Archimedes, Ilmuan Syracuse, Yunani Kuno.')
st.markdown('###')
st.subheader('2. Persamaan Hukum Archimedes')
st.write('Gaya apung yang bekerja pada suatu benda yang dicelupkan sebagian atau seluruhnya ke dalam suatu fluida sama dengan berat fluida yang dipindahkan oleh benda tersebut. Berikut persamaannya:')
st.markdown("<img src='https://unjac-my.sharepoint.com/personal/shelvyokvia_1302620035_mhs_unj_ac_id/Documents/120/Website%20Chatbot/image/Picture14.png?Web=1' width='400' style='display: block; margin: 0 auto;'>", unsafe_allow_html=True)
st.write('')
st.write('Keterangan:')
st.write(r'$$F = \text{Gaya} \,(N)$$')
st.write(r'$$\rho = \text{Densitas atau massa jenis} \, (kg/m^3)$$')
st.write(r'$$V = \text{volume fluida dipindahkan} \,(m^3)$$')
st.write(r'$$g = \text{percepatan gravitasi} \,(m/s^2)$$')
st.markdown('###')
st.subheader('Keadaan Benda di Fluida')
st.write('Kondisi benda dalam fluida ditentukan oleh resultan gaya apung dan gaya beratnya. Oleh karena itu dibedakan menjadi 3 jenis, yaitu melayang, tenggelam, dan terapung, Untuk penjelasannya lebih detailnya sebagai berikut:')
st.markdown('- MELAYANG')
st.write('Melayang terjadi jika benda seluruhnya tercelup dalam fluida tetapi tidak menyentuh dasar fluida.')
st.markdown("<img src='https://unjac-my.sharepoint.com/personal/shelvyokvia_1302620035_mhs_unj_ac_id/Documents/120/Website%20Chatbot/image/Picture15.png?Web=1' width='200' style='display: block; margin: 0 auto;'>", unsafe_allow_html=True)
left_co, cent_co,last_co = st.columns(3)
with cent_co:
    st.latex(r'\rho_{benda} = \rho_{fluida}')
    st.latex(r'F_A = w_{benda}')
st.markdown('###')
st.markdown('- TENGGELAM')
st.write('Tenggelam terjadi jika benda seluruhnya tercelup dalam fluida dan menyentuh dasar fluida.')
st.markdown("<img src='https://unjac-my.sharepoint.com/personal/shelvyokvia_1302620035_mhs_unj_ac_id/Documents/120/Website%20Chatbot/image/Picture16.png?Web=1' width='200' style='display: block; margin: 0 auto;'>", unsafe_allow_html=True)
left_co, cent_co,last_co = st.columns(3)
with cent_co:
    st.latex(r'\rho_{benda} > \rho_{fluida}')
    st.latex(r'F_A + N = w_{benda}')
    st.latex(r'w_{semu} = (\rho_{benda}-\rho_{fluida}){V_{benda}{g}}')
st.markdown('###')
st.markdown('- TERAPUNG')
st.write('Terapung terjadi jika benda sebagian tercelup di fluida dan sebagian di atas permukaan fluida.')
st.markdown("<img src='https://unjac-my.sharepoint.com/personal/shelvyokvia_1302620035_mhs_unj_ac_id/Documents/120/Website%20Chatbot/image/Picture17.png?Web=1' width='200' style='display: block; margin: 0 auto;'>", unsafe_allow_html=True)
left_co, cent_co,last_co = st.columns(3)
with cent_co:
    st.latex(r'\rho_{benda} < \rho_{fluida}')
    st.latex(r'F_A + N = w_{benda}')
    st.latex(r'\frac{V_{tercelup}}{V_{benda}} = \frac{h_{tercelup}}{h_{benda}} = \frac{\rho_{benda}}{\rho_{fluida}}')
st.write('Keterangan:')
st.write(r'$$\rho_{benda} = \text{Massa jenis benda} \,(kg/m^3)$$')
st.write(r'$$\rho_{fluida} = \text{Massa jenis fluida} \, (kg/m^3)$$')
st.write(r'$$F_A = \text{Gaya apung} \,(N)$$')
st.write(r'$$w_{benda} = \text{Berat Benda} \,(N)$$')
st.write(r'$$V_{tercelup} = \text{Volume benda tercelup} \,(m^3)$$')
st.write(r'$$V_{benda} = \text{Volume benda} \, (m^3)$$')
st.write(r'$$h_{tercelup} = \text{Kedalaman Tercelup} \,(m)$$')
st.write(r'$$h_{benda} = \text{Kedalaman Benda} \,(m)$$')
st.markdown('###')
st.subheader('Penerapan Hukum Archimedes')
st.write('Penerapan hukum Archimedes antara lain yaitu pertama ada kapal laut, di desain agar tetap dalam keadaan terapung di atas air memanfaatkan ruang udara yang dinamakan langbung kapal. Kedua kapal selam, desain kapal selam mampu membuat kapa berada di permukaan air dan melayang di dalam air. Memanfaatkan ruang udara yang mampu diisi dan dikosongkan dengan sistem katup. Ketiga balon udara, balon udara memanfaatkan perbedaan massa jenis udara panas dalam balon yang kecil dengan massa jenis udara dingin di luar balon yang lebih besar, sehingga timbul gaya apung pada balon tersebut.')
st.markdown('###')
st.write('---')

#Header Kelima
st.header('E. Kohesi dan Adhesi')
st.write('Di dalam subbab ini terdapat tiga pembahasan utama, yaitu kohesi dan adhesi, kapilaritas, dan tegangan permukaan. Untuk penjelasan materi dengan singkatnya sebagai berikut:')
st.subheader('1. Tegangan Permukaan')
st.write('Tegangan permukaan merupakan gaya yang berkerja pada tiap satuan panjang bidang permukaan fluida. Tegangan permukaan timbul karena adanya gaya tarik menarik molekul fluida sehingga pada permukaan seolah menimbulkan lapisan tipis yang mempunyai kecenderungan menyusut pada luasan permukaan, itulah yang menyebabkan tetesan air akan berbentuk bulatan saat jatuh di udara. Persamaan tegangan permukaan yaitu:')
left_co, cent_co,last_co = st.columns(3)
with cent_co:
    st.latex(r'\gamma = \frac{F}{d}')
st.write('Untuk lapisan sabun pada kawat U dan kawat L')
with cent_co:
    st.latex(r'\gamma = \frac{F}{2L}')
st.write('Keterangan:')
st.write(r'$$\gamma = \text{tegangan permukaan} \,(N/m)$$')
st.write(r'$$F = \text{gaya permukaan} \,(N)$$')
st.write(r'$$d = \text{Panjang permukaan} \,(m)$$')
st.write(r'$$L = \text{Panjang kawat L} \,(m)$$')
st.write('Terdapat beberapa faktor yang mempengaruhi tegangan permukaan, diantaranya: pertama suhu, semakin tinggi suhu fluida maka tegangan permukaan akan semakin kecil. Kedua kohesi dan adhesi, jika gaya kohesi lebih besar dari gaya adhesi, maka tegangan permukaan akan semakin besar namun jika gaya kohesi lebih kecil dari gaya adhesi, maka tegangan permukaan akan semakin kecil. Ketiga zat terlarut, adanya zat terlarut akan menurunkan tegangan permukaan, antara lain sabun dan detergen.')
st.markdown('###')
st.subheader('2. Kohesi dan Adhesi')
st.write('Kohesi merupakan gaya tarik menarik partikel/molekul sejenis. Pada permukaan fluida dan wadah akan menimbulkan meniscus cembung. Contoh: raksa dalam tabung kaca.')
st.markdown("<img src='https://unjac-my.sharepoint.com/personal/shelvyokvia_1302620035_mhs_unj_ac_id/Documents/120/Website%20Chatbot/image/Picture18.png?Web=1' width='200' style='display: block; margin: 0 auto;'>", unsafe_allow_html=True)
st.write('Adhesi merupakan gaya tarik menarik partikel/molekul yang berbeda jenis. Pada permukaan fluida dan wadah akan menimbulkan meniscus cekung. Contoh: air kopi dalam cangkir keramik.')
st.markdown("<img src='https://unjac-my.sharepoint.com/personal/shelvyokvia_1302620035_mhs_unj_ac_id/Documents/120/Website%20Chatbot/image/Picture19.png?Web=1' width='200' style='display: block; margin: 0 auto;'>", unsafe_allow_html=True)
st.write('Sudut kontak merupakan sudut yang dibetuk oleh permukaan fluida (meniscus) terhadap wadah, untuk meniscus cekung bernilai 0°-90° sedangkan untuk meniscus cembung bernilai 90°-180°. Kondisi fluida di permukaan suatu benda tergantung hubungan kohesi-adhesinya.')
st.markdown("<img src='https://unjac-my.sharepoint.com/personal/shelvyokvia_1302620035_mhs_unj_ac_id/_layouts/15/SkySyncRedir.aspx?Type=2&ResourceId=ae3ec8a7321f454d9963ff4ba06b7d89&View=0' width='200' style='display: block; margin: 0 auto;'>", unsafe_allow_html=True)
st.markdown('###')
st.subheader('3. Kapilaritas')
st.write('Gejala naik atau turunnya permukaan fluida dalam pipa sempit (kapiler). Saat terjadi meniscus cekung permukaan fluida dalam pipa kapiler akan naik, sebaliknya saat terjadi meniscus cembung permukaan fluida dalam pipa kapiler akan turun. Contoh beberapa fenomena kapilaritas seperti tisu yang basah jika dicelupkan ke air, naiknya air tanah melalui akar tumbuhan, pori-pori dinding menyerap air tanah.')
st.markdown("<img src='https://unjac-my.sharepoint.com/personal/shelvyokvia_1302620035_mhs_unj_ac_id/Documents/120/Website%20Chatbot/image/Picture21.png?Web=1' width='200' style='display: block; margin: 0 auto;'>", unsafe_allow_html=True)
left_co, cent_co,last_co = st.columns(3)
with cent_co:
    st.latex(r'h = \frac{{2\gamma}{cos\theta}}{{\rho}{g}{r}}')
st.write('Keterangan:')
st.write(r'$$h = \text{naik/turun permukaan fluida } \,(m)$$')
st.write(r'$$\gamma = \text{tegangan permukaan} \,(N/m)$$')
st.write(r'$$\theta = \text{Sudut kontak}$$')
st.write(r'$$\rho = \text{Massa jenis fluida} \,(N/m^3)$$')
st.write(r'$$r = \text{jari-jari pipa kapiler} \,(m)$$')
st.write(r'$$g = \text{percepatan gravitasi} \,(m/s^2)$$')
st.markdown('###')
st.write('---')

#Header Keenam
st.header('F. Hukum Stokes')
st.write('Di dalam subbab hukum stokes terdapat beberapa pembahasan utama, yaitu viskositas, kecepatan terminal, dan hukum stokes. Untuk lebih lengkapnya perhatikan penjelasan berikut ini:')
st.subheader('1. Viskositas')
st.write('Tingkat ketahanan fluida terhadap deformasi atau perubahan bentuk ketika mengalir, secara sederhana adalah tingkat kekentalan fluida. Semakin tinggi viskositas fluida maka fluida tersebut akan semakin kental. Jika fluida kental maka sulit berubah bentuk ketika mengalir, sebaliknya jika fluida encer maka mudah berubah bentuk ketika mengalir. Contoh fluida viskositas tinggi, yaitu madu, minyak goreng, kental manis, dan kecap manis. Contoh fluida viskositas rendah, yaitu alcohol, air, bensin, dan cuka. Secara matematis viskositas merupakan perbandingan antara tegangan geser dengan kecepatan fluida pada lapisan atau tebal tertentu. Berikut ini persamaan matematisnya:')
left_co, cent_co,last_co = st.columns(3)
with cent_co:
    st.latex(r'\eta = \frac{{F/A}}{{v/y}}')
st.write('Keterangan:')
st.write(r'$$\eta = \text{koefesien viskositas} \,(Pa.s)$$')
st.write(r'$$F = \text{gaya geser} \,(N)$$')
st.write(r'$$A = \text{luas bidang} \,(m^2)$$')
st.write(r'$$v = \text{kecepatan fluida} \,(m/s)$$')
st.write(r'$$y = \text{tebal lapisan fluida} \,(m)$$')
st.write('Ada beberapa faktor yang mempengaruhi viskositas, yaitu tekanan karena semakin tinggi tekanan fluida maka viskositas akan semakin besar, suhu karena semakin tinggi suhu fluida maka viskositas akan semakin kecil, konsentrasi larutan karena semakin tinggi konsentrasi zat terlarut dalam fluida maka viskositasnya akan semakin besar, serta ukuran dan massa molekul karena semakin besar ukuran dan massa molekul maka viskositasnya akan semakin besar.')
st.write('Viscometer merupakan alat yang digunakan untuk mengukur viskositas suatu fluida, dengan memanfaatkan perbandingan kecepatan alir fluida dalam pipa maupun ketahanan fluida terhadap gaya untuk menggerakkan fluida. Ada beberapa jenis viscometer, antara lain viskometer ostwald, viskometer hoppler, viskometer cup and bob, dan viskometer Brookfield (cone and plate).')
st.markdown('###')
st.subheader('2. Hukum Stokes')
st.write('Bunyi hukum Stokes yaitu, “Jika sebuah benda bergerak dalam fluida yang statis (diam) maka benda tersebut akan mendapat gaya hambat yang besarnya sebanding dengan viskositas fluida dan tetapan geometri benda tersebut.”')
st.markdown("<img src='https://unjac-my.sharepoint.com/personal/shelvyokvia_1302620035_mhs_unj_ac_id/Documents/120/Website%20Chatbot/image/Picture22.png?Web=1' width='100' style='display: block; margin: 0 auto;'>", unsafe_allow_html=True)
left_co, cent_co,last_co = st.columns(3)
with cent_co:
    st.latex(r'F_s = {k}{\eta}{v}')
st.write('Untuk benda berbentuk bola, maka:')
with cent_co:
    st.latex(r'k = {6}{\pi}{r}')
    st.latex(r'F_s = {6}{\pi}{r}{\eta}{v}')
st.write('Keterangan:')
st.write(r'$$F_s = \text{Gaya hambat stokes } \,(N)$$')
st.write(r'$$k = \text{Tetapan geometri benda} \,(m)$$')
st.write(r'$$\eta = \text{Koefesien viskositas} \,(Pa.s)$$')
st.write(r'$$r = \text{Jari-jari benda/bola} \,(m)$$')
st.write(r'$$\pi =\,22/7 \text{ atau } \,3,14$$')
st.write(r'$$v = \text{Kecepatan benda} \,(m/s)$$')
st.markdown('###')
st.subheader('3. Kecepatan Terminal')
st.markdown("<img src='https://unjac-my.sharepoint.com/personal/shelvyokvia_1302620035_mhs_unj_ac_id/Documents/120/Website%20Chatbot/image/Picture23.png?Web=1' width='100' style='display: block; margin: 0 auto;'>", unsafe_allow_html=True)
st.write('Kecepatan terminal merupakan kecepatan maksimal suatu benda apabila jatuh di dalam suatu fluida. yang tercapai saat terjadi kesetimbangan gaya pada benda yang bergerak dalam fluida. Kecepatan terminal terjadi ketika (w = Fa + Fs) sehingga resultan gaya sama dengan nol dan benda tidak mengalami percepatan lagi. Contohnya yaitu penerjun paying yang jatuh pada kecepatan terminal rendah saat membuka payungnya.')

